## This is my new note book

In [1]:
import numpy as np


In [17]:
data=np.array(2d array)

SyntaxError: invalid decimal literal (2712562489.py, line 1)

In [16]:
print(data)

50


In [18]:
data=np.zeros([2,3])

In [19]:
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
data[:]=3

In [21]:
data

array([[3., 3., 3.],
       [3., 3., 3.]])

In [22]:
data[:-1]

array([[3., 3., 3.]])

In [26]:
data1=np.random.rand()

In [27]:
data1

0.23153577732474773

In [31]:
data=np.random.random([2,3])

In [32]:
data

array([[0.55460236, 0.46704644, 0.42551638],
       [0.67580559, 0.04560239, 0.32928051]])