## This is the first run

In [1]:
import numpy as np

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [66]:
array = np.zeros([15,5])
array[1,2]=10
print(array)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [70]:
np.shape(array)

(15, 5)

In [80]:
array[1:3]=10
print(array)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [84]:
array[1][2]

10.0

In [121]:
rows,cols=10,5
array = np.random.randint(0,20, size=(rows, cols))
print(array)

[[ 7  5 14 16 16]
 [ 4  1 15  8  4]
 [11  6  4 14  9]
 [ 4 18 19  1  5]
 [15  0  2 16 14]
 [13  3 10  2  3]
 [12 18  4 14 11]
 [ 7 19 13  0  8]
 [ 4  4 12  3  6]
 [ 2  1 18  2 14]]
