## This is the first run

In [1]:
import numpy as np

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [66]:
array = np.zeros([15,5])
array[1,2]=10
print(array)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [70]:
np.shape(array)

(15, 5)

In [80]:
array[1:3]=10
print(array)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [84]:
array[1][2]

10.0

In [115]:
array = np.random.randint(0,20, size=(10, 5))
print(array)

[[12 19  5 17  7]
 [ 1  9  0 12  6]
 [16 17 15 14 13]
 [ 1  5  4  8 15]
 [ 6 17 17  3 14]
 [13 18  3  6 13]
 [18  2  0  3  5]
 [ 6  8 14  5 16]
 [ 8 11 11 16 15]
 [ 0 17 12 16 16]]
