## This is my first notebook

In [1]:
import numpy as np

In [4]:
data=np.array([1,2,3,4])


In [8]:
len(data)

4

In [12]:
bigdata=np.zeros([10,5])

In [13]:
print (bigdata)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
bigdata[0][3]=6

In [19]:
print(bigdata)

[[0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6.]
 [0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
dataa=np.random.random([5,5])

In [23]:
print(dataa)

[[0.66299239 0.5800784  0.0805868  0.52067251 0.33672981]
 [0.7161015  0.4365883  0.34185025 0.31552273 0.86865196]
 [0.06356038 0.35831747 0.94959694 0.95729527 0.94457142]
 [0.2643429  0.77695035 0.94032136 0.04604935 0.16257009]
 [0.0848611  0.36355888 0.23248872 0.85974105 0.59191643]]
