# This is my run in Jupiter

In [4]:
# IMPORTS
import numpy as np

In [6]:
 group =np.array(5)

In [21]:
bigdata=np.empty([10,4])
print(bigdata)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
bigdata=np.zeros([10,4])
print(bigdata)
np.shape(bigdata)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(10, 4)

In [37]:
bigdata=np.zeros([2,3])
print(bigdata)
np.shape(bigdata)
bigdata[0:1]=10


[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
array=np.zeros([2,3])
print(array)
np.shape(array)
array[0:1]=10

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
array = np.random.randint(0,3, size=(10, 5))
print(array)

[[2 0 2 0 2]
 [2 0 0 2 1]
 [0 2 2 1 1]
 [1 1 1 2 0]
 [0 2 0 1 0]
 [2 0 2 2 2]
 [2 0 2 0 0]
 [2 1 1 0 2]
 [2 2 1 2 2]
 [2 2 0 0 2]]
